// LOGIN
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAILURE = 'ADMIN_LOGIN_FAILURE';

// USERS COUNT
export const GET_USERS_COUNT_REQUEST = 'GET_USERS_COUNT_REQUEST';
export const GET_USERS_COUNT_SUCCESS = 'GET_USERS_COUNT_SUCCESS';
export const GET_USERS_COUNT_FAILURE = 'GET_USERS_COUNT_FAILURE';

// GET ALL USERS
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

// DELETE USERS
export const DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE';

// UPDATE USERS
export const UPDATE_USERS_ROLE_REQUEST = 'UPDATE_USERS_ROLE_REQUEST'
export const UPDATE_USERS_ROLE_SUCCESS = 'UPDATE_USERS_ROLE_SUCCESS'
export const UPDATE_USERS_ROLE_FAILURE = 'UPDATE_USERS_ROLE_FAILURE'


// GET TASKS
export const GET_TASKS_REQUEST = 'GET_TASKS_REQUEST'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const GET_TASKS_FAILURE = 'GET_TASKS_FAILURE'


// DELETE TASKS
export const DELETE_TASKS_REQUEST = 'DELETE_TASKS_REQUEST'
export const DELETE_TASKS_SUCCESS = 'DELETE_TASKS_SUCCESS'
export const DELETE_TASKS_FAILURE = 'DELETE_TASKS_FAILURE'

// Filtered Tasks 
export const FILTERED_TASKS_REQUEST = 'FILTERED_TASKS_REQUEST'
export const FILTERED_TASKS_SUCCESS = 'FILTERED_TASKS_SUCCESS'
export const FILTERED_TASKS_FAILURE = 'FILTERED_TASKS_FAILURE'

// Search Tasks
export const SEARCH_TASKS_SUCCESS = 'SEARCH_TASKS_SUCCESS'



// Assign Info

export const ASSIGN_USERS_REQUEST = "ASSIGN_USERS_REQUEST";
export const ASSIGN_USERS_SUCCESS = "ASSIGN_USERS_SUCCESS";
export const ASSIGN_USERS_FAILURE = "ASSIGN_USERS_FAILURE";


// Update Tasks
export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE'